version: "3.8"

services:
  api:
    build:
      target: production
      context: .
      args:
        - APP_PORT=$APP_PORT
    ports:
      - "$APP_PORT:$APP_PORT"

  api-dev:
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - APP_PORT=$APP_PORT
    ports:
      - "$APP_PORT:$APP_PORT"
      - "9229:9229"
    volumes:
      - .:/project
      - node_modules:/project/node_modules/

volumes:
  node_modules:
